name: Go CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x, 1.23.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Set up Go module authentication
      run: git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      env:
        GITHUB_TOKEN: ${{ secrets.GO_MODULE_TOKEN }}

    - name: Configure Go private modules
      run: go env -w GOPRIVATE=github.com/TrustSight-io/*

    - name: Install dependencies
      run: go mod download

    - name: Verify code formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          gofmt -s -l .
          echo "Code is not properly formatted. Run 'go fmt ./...' to fix"
          exit 1
        fi

    - name: Run linting
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout 5m

    - name: Run unit tests
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Generate coverage report
      run: go tool cover -html=coverage.txt -o coverage.html

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.go-version }}
        path: coverage.html

    - name: Run integration tests
      run: |
        echo "Running integration tests in providers package..."
        go test -tags=integration -v ./providers/...
        echo "Running integration tests in sdkwrappers package..."
        go test -tags=integration -v ./sdkwrappers/...

    - name: Build
      run: go build -v ./...
